name: Bug report
description: Report a reproducible problem
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: Thanks for reporting a bug. Please fill in details below.
  - type: input
    id: summary
    attributes:
      label: Summary
      placeholder: Short description of the bug
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Run ...
        2. Press ...
        3. Observe ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: input
    id: env
    attributes:
      label: Environment
      placeholder: macOS version, terminal, bun --version, brew --version
